port: 7890           # HTTP 代理端口
socks-port: 7891     # Socks 端口
redir-port: 7892     # Redir 端口
mixed-port: 7893     # 混合端口
allow-lan: true      # 允许局域网连接
bind-address: "*"    # 地址绑定
mode: rule           # 规则模式
log-level: info      # 日志级别
ipv6: false          # IPV6开关
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
   - 119.29.29.29
   - 223.5.5.5
   - 208.67.222.222:5353
   - 208.67.220.220:5353
  nameserver:
   - https://1.12.12.12/dns-query
   - https://223.5.5.5/dns-query
  fallback:
   - https://1.0.0.1/dns-query#默认
   - https://dns.google/dns-query#默认
   - https://doh.opendns.com/dns-query#默认
  fallback-filter:
     geoip: true
     geoip-code: CN
     ipcidr:
       - 240.0.0.0/4
