port: 7890           # HTTP 代理端口
socks-port: 7891     # Socks 端口
redir-port: 7892     # Redir 端口
mixed-port: 7893     # 混合端口
allow-lan: true      # 允许局域网连接
bind-address: "*"    # 地址绑定
mode: rule           # 规则模式
log-level: info      # 日志级别
ipv6: false          # IPV6开关
external-controller: 127.0.0.1:9090
# DNS 配置
dns:
  cache-algorithm: arc
  enable: false # 关闭将使用系统 DNS
  prefer-h3: true # 开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:53 # 开启 DNS 服务器监听
  # ipv6: false # false 将返回 AAAA 的空结果
  # ipv6-timeout: 300 # 单位：ms，内部双栈并发时，向上游查询 AAAA 时，等待 AAAA 的时间，默认 100ms
  # 用于解析 nameserver，fallback 以及其他 DNS 服务器配置的，DNS 服务域名
  # 只能使用纯 IP 地址，可使用加密 DNS
  default-nameserver:
   - 119.29.29.29
   - 223.5.5.5
   - 208.67.222.222:5353
   - 208.67.220.220:5353
  enhanced-mode: fake-ip # or redir-host

  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置

  # use-hosts: true # 查询 hosts

  # 配置不使用 fake-ip 的域名
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # DNS 主要域名配置
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver:
   - quic://223.5.5.5
   - quic://223.6.6.6
   - https://1.12.12.12/dns-query
   - https://120.53.53.53/dns-query
   
  # 当配置 fallback 时，会查询 nameserver 中返回的 IP 是否为 CN，非必要配置
  # 当不是 CN，则使用 fallback 中的 DNS 查询结果
  # 确保配置 fallback 时能够正常查询
  fallback:
    - https://1.0.0.1/dns-query#默认
    - https://dns.google/dns-query#默认
    - https://doh.opendns.com/dns-query#默认

  # 配置 fallback 使用条件
  fallback-filter:
    geoip: true # 配置是否使用 geoip
    geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
    #   配置强制 fallback，优先于 IP 判断，具体分类自行查看 geosite 库
    geosite:
     - gfw
  # 如果不匹配 ipcidr 则使用 nameservers 中的结果
   ipcidr:
     - 240.0.0.0/4
   domain:
     - '+.google.com'
     - '+.facebook.com'
     - '+.youtube.com'
