port: 7890           # HTTP 代理端口
socks-port: 7891     # Socks 端口
redir-port: 7892     # Redir 端口
mixed-port: 7893     # 混合端口
allow-lan: true      # 允许局域网连接
bind-address: "*"    # 地址绑定
mode: rule           # 规则模式
log-level: info      # 日志级别
ipv6: false          # IPV6开关
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
   - 119.29.29.29
   - 223.5.5.5
   - 208.67.222.222:5353
   - 208.67.220.220:5353
  nameserver:
   - quic://223.5.5.5
   - quic://223.6.6.6
   - https://1.12.12.12/dns-query
   - https://120.53.53.53/dns-query
  fallback:
   - https://1.0.0.1/dns-query
   - https://dns.google/dns-query
   - https://doh.opendns.com/dns-query
  fake-ip-filter:
    - +.+m2m
    - +.$injections.adguard.org
    - +.$local.adguard.org
    - +.+_tcp
    - +.+bogon
    - +.+_msdcs
    - +.+lan
    - +.+localdomain
    - +.home.arpa
    - +.10.in-addr.arpa
    - +.16.172.in-addr.arpa
    - +.17.172.in-addr.arpa
    - +.18.172.in-addr.arpa
    - +.19.172.in-addr.arpa
    - +.20.172.in-addr.arpa
    - +.21.172.in-addr.arpa
    - +.22.172.in-addr.arpa
    - +.23.172.in-addr.arpa
    - +.24.172.in-addr.arpa
    - +.25.172.in-addr.arpa
    - +.26.172.in-addr.arpa
    - +.27.172.in-addr.arpa
    - +.28.172.in-addr.arpa
    - +.29.172.in-addr.arpa
    - +.30.172.in-addr.arpa
    - +.31.172.in-addr.arpa
    - +.168.192.in-addr.arpa
    - +.254.169.in-addr.arpa
    - dns.msftncsi.com
    - "*.srv.nintendo.net"
    - "*.stun.playstation.net"
    - xbox.*.microsoft.com
    - "*.xboxlive.com"
    - "*.turn.twilio.com"
    - "*.stun.twilio.com"
    - stun.syncthing.net
  geoip: true
  geoip-code: CN
  ipcidr:
    - 240.0.0.0/4
