name: Auto Update

on:
  schedule:
    - cron: '0 7 * * *'  # 每天早上7点执行

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'  # 使用你的Python版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: python Actions/clash.py  # 替换成你的脚本文件名
